# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7c382f15b132920a89756a0df300439b"
application_url = "https://numerous-depend-fu-mobility.trycloudflare.com"
embedded = true
name = "Billinguo Order"
handle = "billinguo-order"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, read_orders, read_customers"

[auth]
redirect_urls = [
  "https://numerous-depend-fu-mobility.trycloudflare.com/auth/callback",
  "https://numerous-depend-fu-mobility.trycloudflare.com/auth/shopify/callback",
  "https://numerous-depend-fu-mobility.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "ashutoshdev.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
